stages:
  - test_tools
  - test_check_database_combine

unit-test:
  stage: test_tools
  # https://hub.docker.com/r/library/python/tags/
  image: python:latest
  before_script:
    - python3 -V  # Print out python version for debugging
    - pip3 install pandas tqdm coverage
  script:
      - coverage run -m unittest test_tools.py
      - coverage report
      - coverage xml
      - coverage html
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov

unit-test:
  stage: test_check_database_combine
  # https://hub.docker.com/r/library/python/tags/
  image: python:latest
  before_script:
    - python3 -V  # Print out python version for debugging
    - pip3 install pandas coverage
  script:
      - coverage run -m unittest test_checkCombine.py
      - coverage report
      - coverage xml
      - coverage html
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov