stages:
  - test

unit-test:
  stage: test
  # https://hub.docker.com/r/library/python/tags/
  image: python:latest
  before_script:
    - python3 -V  # Print out python version for debugging
    - pip3 install pandas tqdm coverage
  script:
      - coverage run -m unittest
      - coverage report
      - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobrtura
        path: coverage.xml