import argparse

from tidy import gatherAssemblies

parser = argparse.ArgumentParser()
parser.add_argument('tsv', help="Path to the .tsv file generated by `-m` switch")
parser.add_argument('dir', help="Path to the directory generated by `-o` parameter")
parser.add_argument('--excludeList', help="Exclusion list file, one item per line",
                    default="")
parser.add_argument('--maxCtg', type=int,
                    help="Maximum number of contigs that a genome will be kept.",
                    default=None)
parser.add_argument('--targetDir', type=str,
                    help='Valid assemblies will be copied to this directory.',
                    default=None)
args = parser.parse_args()

gatherAssemblies(args)
