import argparse

from tools import getInfoFrom, getExclusion, filterDownloads

def processArgs():
    parser = argparse.ArgumentParser()
    parser.add_argument('tsv', help="Path to the .tsv file generated by `-m` switch")
    parser.add_argument('dir', help="Path to the directory generated by `-o` parameter")
    parser.add_argument('--excludeList', help="Exclusion list file, one item per line",
                        default="")
    parser.add_argument('--maxCtg', type=int,
                        help="Maximum number of contigs that a genome will be kept.",
                        default=None)
    args = parser.parse_args()
    return args


def main():
    args = processArgs()
    strains = getInfoFrom(args)
    exclusions = getExclusion(args.excludeList)
    validAssemblies, excludedAccs, skippedAccs, tooManyContigs = \
        filterDownloads(strains, exclusions, args.maxCtg)

if __name__ == "__main__":
    main()